homie_server/homie_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from homie_server.views import *
# from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include("social.apps.django_app.urls", namespace="social")),
    url(r'^', include("users.urls", namespace="users")),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^$', HomeView.as_view(), name="home"),
]

homie_server/posts/urls.py
from django.conf.urls import url

from posts.views import *


urlpatterns = [
    url(r'^$', PostListView.as_view(), name="list"),
    url(r'^new/$', PostCreateView.as_view(), name="create"),
    url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),
    url(r'^(?P<slug>\w+)/$', PostDetailView.as_view(), name="detail"),
    url(r'^(?P<post_id>\d+)/edit/$', edit, name="edit"),
    url(r'^(?P<post_id>\d+)/update/$', update, name="update"),
    url(r'^(?P<post_id>\d+)/delete/$', delete, name="delete"),
]

homie_server/posts/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from users.models import User


class PostManager(models.Manager):
    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    user = models.ForeignKey(User)

    hash_id = models.CharField(
        max_length=8,
        blank=True,
        null=True,
    )

    title = models.CharField(
        max_length=120,
    )

    content = models.TextField()

    is_public = models.BooleanField(
        default=True,
    )

    careate_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "slug": self.hash_id,
            },
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )

homie_server/posts/views/base.py
from django.views.generic.list import View

from posts.models import Post


class PostBaseView(View):
    model = Post

homie_server/posts/views/create.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.shortcuts import redirect, render
from .base import PostBaseView


class PostCreateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "posts/new.html",
            context={},
        )

    def post(tself, request, *args, **kwargs):

        title = request.POST.get("title")
        content = request.POST.get("content")
        post = request.user.post_set.create(
            title=title,
            content=content,
        )
        return redirect(reverse("posts:create"))


class PostCreateConfirmView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        return redirect(reverse("posts:create"))

    def post(self, request, *args, **kwargs):
        title = request.POST.get("title")
        content = request.POST.get("content")

        return render(
            request,
            "posts/confirm.html",
            context={
                "title": title,
                "content": content,
            },
        )

homie_server/posts/views/delete.py
from django.core.urlresolvers import reverse
from django.shortcuts import redirect

from posts.models import Post


def delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect(
        reverse("posts:list"),
    )

homie_server/posts/views/detail.py
from django.views.generic.detail import DetailView

from .base import PostBaseView


class PostDetailView(PostBaseView, DetailView):
    template_name = "posts/detail.html"
    slug_field = "hash_id"
#         request,
#         "posts/detail.html",
#         context={
#             "post": Post.objects.get(id=post_id),
#         },
#     )

homie_server/posts/views/edit.py
from django.shortcuts import render

from posts.models import Post


def edit(request, post_id):
    return render(
        request,
        "posts/edit.html",
        context={
            "post": Post.objects.get(id=post_id),
        }
    )

homie_server/posts/views/list.py
from django.views.generic.list import ListView
from django.core.paginator import Paginator

from .base import PostBaseView


class PostListView(PostBaseView, ListView):
    template_name = "posts/list.html"
    context_object_name = "posts"

    def get_paginate_by(self, queryset):
        return self.request.GET.get("per", 5)
#     def get_queryset(self):
#         queryset = super(PostListView, self).get_queryset()
#         return queryset.filter(is_public=True)
# def list(request):
#     page = request.GET.get("page", 1)
#     per = request.GET.get("per", 5)
#     paginator = Paginator(Post.objects.public(), per)
#     posts = paginator.page(page)
#     return render(
#         request,
#         "posts/list.html",
#         context={
#             "posts": posts,
#         },
#     )

homie_server/posts/views/new.py
from django.shortcuts import render


def new(request):
    return render(
        request,
        "posts/new.html",
        context={},
    )

homie_server/posts/views/update.py
from django.shortcuts import redirect

from posts.models import Post


def update(request, post_id):
    post = Post.objects.get(id=post_id)

    title = request.POST.get("title")
    content = request.POST.get("content")

    post.title = title
    post.content = content

    post.save()

    return redirect(post)

homie_server/posts/templates/posts/confirm.html
{% extends "base.html" %}


{% block content %}
<h1>Confirm Post</h1>

<section>
    <h3>{{ title}}</h3>
    <p>{{ content }}</p>

    <form action="{% url "posts:create" %}" method="POST">
        {% csrf_token %} 
        <p>위의 정보로 포스트를 생성하시겠습니까?</p>
        <input type="hidden" name="title" value="{{ title }}">
        <input type="hidden" name="content" value="{{ content }}">
        <input type="submit">
    </form>
</section>
{% endblock %}

homie_server/posts/templates/posts/detail.html
{% extends "base.html" %}


{% block content %}
<h1>Posts Detail</h1>
<section>
    <ul>
        <li><h3>{{ post.title }}</h3></li>
        <p>{{ post.content }}</p>
        <li><a href="{% url "posts:edit" post_id=post.id %}">Edit</a></li>
        <li><a href="{% url "posts:delete" post_id=post.id %}">Delet</a></li>
    </ul>
</setion>
{% endblock %}

homie_server/posts/templates/posts/edit.html
{% extends "base.html" %}


{% block content %}
<h1>Edit Post</h1>
{% include "posts/form.html" with action=post.get_update_url %}
{% endblock %}

homie_server/posts/templates/posts/form.html
<form action="{{ action }}" method="POST">
    {% csrf_token %}
    <input type="text" name="title" placeholder="제목" value="{% if post %}{{ post.title }}{% endif %}" required>
    <textarea name="content" placeholder="본문" value="{% if post %}{{ post.content }}{% endif %}"></textarea>
    <input type="submit" value="publish">
</form>

homie_server/posts/templates/posts/list.html
{% extends "base.html" %}


{% block content %}
<h1>Post List</h1>

<section>
    <ul>
        {% for post in posts %}
            <li>
            <a href="{{ post.get_absolute_url }}">
                    <h3>{{ post.title }}</h3>
                </a>
            </li>
            <p>{{ post.content }}</p>
            <p>{{ post.careate_at }}</p>
            <a href="{{ post.get_absolute_url }}">상세페이지 바로가기</a>
        {% endfor %}
    </ul>
</section>
{% endblock %}

homie_server/posts/templates/posts/new.html
{% extends "base.html" %}


{% block content %}
    <h1>New Post</h1>
{% include "posts/form.html" with action="/posts/confirm/" %}
{% endblock %}