homie_server/homie_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from homie_server.views import *
# from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include("social.apps.django_app.urls", namespace="social")),
    url(r'^', include("users.urls", namespace="users")),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^$', HomeView.as_view(), name="home"),
]

homie_server/posts/urls.py
from django.conf.urls import url

from posts.views import *


urlpatterns = [
    url(r'^$', PostListView.as_view(), name="list"),
    url(r'^new/$', PostCreateView.as_view(), name="create"),
    url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),
    url(r'^(?P<slug>\w+)/$', PostDetailView.as_view(), name="detail"),
    url(r'^(?P<post_id>\d+)/edit/$', edit, name="edit"),
    url(r'^(?P<post_id>\d+)/update/$', update, name="update"),
    url(r'^(?P<post_id>\d+)/delete/$', delete, name="delete"),
]

homie_server/users/urls.py
from django.conf.urls import url

from users.views import *

from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^my/page/$', MypageView.as_view(), name="mypage"),
]

homie_server/homie_server/views/home.py
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect

from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)

        context["site_name"] = "homie"
        return context

homie_server/homie_server/templates/partials/footer.html
<footer>
    <h1>Footer<h1>
</footer>

homie_server/homie_server/templates/partials/header.html
<header>
    <h1>Header</h1>

    <section>
        <ul>
            <li><a href="{% url "home" %}">Home</a></li>
            <li><a href="{% url "posts:list" %}">Post List</a></li>
            <li><a href="{% url "posts:create" %}">Post Create</a></li>
        </ul>
        {% if request.user.is_authenticated %}
            <ul>
                <li><a href="{% url "users:mypage" %}">User name : {{ request.user.username }}</a></li>
                <li><a href="{% url "users:logout" %}"><spen>{{ user }}</spen>님 Logout</a></li>
            </ul>
        {% else %}
            <ul>
                <li><a href="{% url "users:login" %}">Login</a></li>
                <li><a href="{% url "users:signup" %}">Signup</a></li>
            </ul>
        {% endif %}
    </section>
</header>

homie_server/homie_server/templates/partials/messages.html
{% if messages %}
    <section id="messages">
        <ul>
        {% for message in messages %}
            <li class="{{ message.tags }}" role="alert">
                <p>{{ message }}</p>
            </li>
        {% endfor %}
        </ul>
    </section>
{% endif %}