homie_server/homie_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from homie_server.views import *
# from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url('', include("social.apps.django_app.urls", namespace="social")),
    url(r'^', include("users.urls", namespace="users")),
    url(r'^posts/', include("posts.urls", namespace="posts")),
    url(r'^$', HomeView.as_view(), name="home"),
]

homie_server/posts/urls.py
from django.conf.urls import url

from posts.views import *


urlpatterns = [
    url(r'^$', PostListView.as_view(), name="list"),
    url(r'^new/$', PostCreateView.as_view(), name="create"),
    url(r'^confirm/$', PostCreateConfirmView.as_view(), name="confirm"),
    url(r'^(?P<slug>\w+)/$', PostDetailView.as_view(), name="detail"),
    url(r'^(?P<post_id>\d+)/edit/$', edit, name="edit"),
    url(r'^(?P<post_id>\d+)/update/$', update, name="update"),
    url(r'^(?P<post_id>\d+)/delete/$', delete, name="delete"),
]

homie_server/users/urls.py
from django.conf.urls import url

from users.views import *

from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^signup/$', SignupView.as_view(), name="signup"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^my/page/$', MypageView.as_view(), name="mypage"),
]

homie_server/posts/models/post.py
from django.db import models
from django.core.urlresolvers import reverse
from users.models import User


class PostManager(models.Manager):
    def public(self):
        return self.filter(is_public=True)


class Post(models.Model):

    user = models.ForeignKey(User)

    hash_id = models.CharField(
        max_length=8,
        blank=True,
        null=True,
    )

    title = models.CharField(
        max_length=120,
    )

    content = models.TextField()

    is_public = models.BooleanField(
        default=True,
    )

    careate_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "posts:detail",
            kwargs={
                "slug": self.hash_id,
            },
        )

    def get_update_url(self):
        return reverse(
            "posts:update",
            kwargs={
                "post_id": self.id,
            }
        )

homie_server/users/models/user.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    phonenumber = models.CharField(
        max_length=16,
        blank=True,
        null=True,
    )

    useremail = models.CharField(
        max_length=64,
        blank=True,
        null=True,
    )

    address = models.CharField(
        max_length=64,
        blank=True,
        null=True,
    )

    careate_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.username

homie_server/users/views/login.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.conf import settings
from django.shortcuts import render, redirect
from django.views.generic import View


class LoginView(View):

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "users/login.html",
            context={},
        )

    def post(self, request, *args, **kwargs):

        username = request.POST.get("username")
        password = request.POST.get("password")
        next_url = request.POST.get("next_url") or reverse("users:mypage")
        # FIXME: redirect to home

        user = authenticate(
            username=username,
            password=password,
        )

        if user:
            login(request, user)

            messages.add_message(
                request,
                messages.SUCCESS,
                settings.LOGIN_SUCCESS_MESSAGE,
            )

            return redirect(next_url)

        return redirect(reverse("users:login"))

homie_server/users/views/logout.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.views.generic import View


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(
            request,
            messages.SUCCESS,
            settings.LOGOUT_SUCCESS_MESSAGE,
        )

        return redirect(reverse("home"))

homie_server/users/views/mypage.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class MypageView(LoginRequiredMixin, TemplateView):
    template_name = "users/mypage.html"
# class MypageView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         return render(
#             request,
#             "users/mypage.html",
#             context={},
#         )
# @login_required
# def mypage(request):
#     return render(
#         request,
#         "users/mypage.html",
#         context={},
#     )

homie_server/users/views/signup.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.shortcuts import render, redirect


class SignupView(View):

    def get(self, request, *args, **kwargs):
        return render(
            request,
            "users/signup.html",
            context={},
        )

    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")
        phonenumber = request.POST.get("phonenumber")
        useremail = request.POST.get("username")
        address = request.POST.get("address")

        # TODO: validateions (username)

        user = get_user_model().objects.create_user(
            username=username,
            password=password,
            phonenumber=phonenumber,
            useremail=useremail,
            address=address,
        )

        messages.add_message(
            request,
            messages.SUCCESS,
            settings.SIGNUP_SUCCESS_MESSAGE,
        )

        return redirect(reverse("home"))

homie_server/users/templates/users/login.html
{% extends "base.html"%}

{% block content %}
    <h1>Login</h1>

    <section>
        <form action="{% url "users:login" %}" method="POST">
        {% csrf_token %}
            <input type="hidden" name="next_url" value="{{ request.GET.next }}"></br>
            <input type="text" name="username" placeholder="username" required></br>
            <input type="password" name="password" placeholder="password" required></br>
            <input type="submit" value="login">
        </form>
    </section>
    <section>
        <ul>
            <li>
            <a href="{% url "social:begin" backend="facebook" %}">페이스북으로 로그인하기</a>
            </li>
        </ul>
        <ul>
            <li>
            <a href="{% url "social:begin" backend="kakao" %}">카카오로 로그인하기</a>
            </li>
        </ul>
    </section>
{% endblock %}

homie_server/users/templates/users/mypage.html
{% extends "base.html"%}


{% block content %}
<h1>My Page</h1>
    <section>
        <p>{{ request.user.username }}의 마이페이지입니다.</p>
        <h2>내가 쓴 글 ( {{ request.user.post_set.count }} )</h2>
        <ul>
            {% for post in request.user.post_set.all %}
            <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

homie_server/users/templates/users/signup.html
{% extends "base.html"%}

{% block content %}
    <h1>Signup</h1>
    <section>
        <form action="{% url "users:signup" %}" method="POST">
            {% csrf_token %}
            <input type="text" name="username" placeholder="username" required></br>
            <input type="password" name="password" placeholder="password" required></br>
            <input type="tel" name="phonenumber" placeholder="phonenumber" required></br>
            <input type="email" name="useremail" placeholder="useremail" required></br>
            <input type="text" name="address" placeholder="address" required></br>
            <input type="submit" value="signup">
        </form>
    </section>

    <section>
        <ul>
            <li>
            <a href="{% url "social:begin" backend="facebook" %}">페이스북으로 회원가입하기</a>
            </li>
        </ul>
        <ul>
            <li>
            <a href="{% url "social:begin" backend="kakao" %}">카카오로 회원가입하기</a>
            </li>
        </ul>
    </section>
{% endblock %}